### ISSUE TITLE
How to get it working in cron

### ISSUE THREAD

**Issue by jefro108** [bahamas10/zfs-prune-snapshots#11] opened 2021-01-07 11:39 UTC
I've tried using the correct path `/usr/local/bin/zfs-prune-snapshots 1M` but then I get the message `Error! zfs command not found. Are you on the right machine?`

Any clue as to what I'm doing wrong?

**Comment by jefro108** [comment] 2021-01-11 21:07
In the code where it had zfs I updated it with the full path which in my case was `/sbin/zfs` and now it works in cron.

**Comment by yuriw** [comment] 2021-01-13 17:58
Seems to work for me as:
copied `zfs-prune-snapshots` to `/usr/bin`
`which zfs-prune-snapshots
/usr/bin/zfs-prune-snapshots`

added to `sudo crontab -e`
`@daily /usr/bin/zfs-prune-snapshots -v 1s`

**Comment by dradux** [comment] 2021-07-30 20:46
Example directly from [author's website](https://www.daveeddy.com/2015/12/05/automatic-zfs-snapshots-and-backups/):

```
11 0 * * * /opt/custom/bin/zfs-prune-snapshots -p automated_daily_   7d   >> /var/log/autosnap.log 2>&1
12 0 * * 0 /opt/custom/bin/zfs-prune-snapshots -p automated_weekly_  4w   >> /var/log/autosnap.log 2>&1
13 0 1 * * /opt/custom/bin/zfs-prune-snapshots -p automated_monthly_ 12M  >> /var/log/autosnap.log 2>&1
14 0 1 1 * /opt/custom/bin/zfs-prune-snapshots -p automated_yearly_  10y  >> /var/log/autosnap.log 2>&1
```

**Comment by bahamas10** [comment] 2021-11-28 00:03
The issue you are seeing is caused by your crontab not having a `$PATH` environmental variable with `zfs` in it.  You can fix this in multiple ways, but it's outside the scope of this `zfs-prune-snapshots` tool to handle managing your `$PATH` variable.  You can:

### 1

Specify the PATH in your cron line (if your cron supports it), ie:

``` cron
0 0 * * * PATH=/bin:/sbin:/usr/bin:/usr/sbin:/whateveryouwant zfs-prune-snapshots ...
```

### 2

Have cron fire off a "helper" script whose job it is to call `zfs-prune-snapshots`, ie:

``` cron
0 0 * * * /path/to/my-helper-program
````

and `my-helper-program` would look something like:

``` sh
#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/whateveryouwant
exec zfs-prune-snapshots ...
```

### 3

Make sure cron is running/started with the proper PATH variable set.

**Comment by bahamas10** [comment] 2021-11-28 00:03
Closing - feel free to reopen if I misunderstood the original issue and something is still broken.

**Closed as completed by bahamas10** 2021-11-28 00:03 UTC
